### PR TITLE
Renamed, moved to subdirs, dropped py2, et al.

### PR DESCRIPTION
**Pull request by smurfix**
Several of those don't work on its own because renaming *and* editing files in the same change is not something git likes to work with.

### CODE REVIEW

**Comment by smurfix** [comment]
OK … so some clean-up seems to be required, might be best to re-base this instead?

**Comment by smurfix** [comment]
Does anybody have an idea where those *_filename fixtures come from?

**Comment by thomascrha** [comment]
I'm going to work of this branch - everything here makes sense and should be merged in.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I am not yet confident to rename the module itself, mainly because I think there is still slight chance that the upstream issues could sort themselves out. Doing this rename would make porting patches a huge PITA.

**Comment by ssbarnea** [comment]
Closed as abandoned, feel free to reopen once fixed. I would try to minimize changes in order to be able to backport changes from "upstream".

**Pull request closed without merging**
